name: satellite-data-exploration-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - dash=2.14.2
  - dash-bootstrap-components=1.5.0
  - plotly=5.19.0
  - pandas=2.2.1
  - pyngrok=5.3.0
  - jupyterlab>=4.0.0